### logback-spring.xml会被自动加载

spring:
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: test/**

server:
  port: 9005
primary:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver # mysql的驱动你可以配置别的关系型数据库
    url: jdbc:mysql://127.0.0.1:3306/abc?useUnicode=true&characterEncoding=utf-8&useSSL=false #数据源地址
    username: name # 用户名
    password: pass # 密码

secondary:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver # mysql的驱动你可以配置别的关系型数据库
    url: jdbc:mysql://127.0.0.1:3306:3306/def?useUnicode=true&characterEncoding=utf-8&useSSL=false #数据源地址
    username: name # 用户名
    password: pass # 密码

mybatis:
  config-location: classpath:mybatis/config.xml

